frr version 8.5.2
frr defaults traditional
hostname isp-r1
no ipv6 forwarding
!
router bgp 65000
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor 172.22.22.100 remote-as 65001
 neighbor 172.22.22.100 description bc-cache1
 neighbor 172.22.22.200 remote-as 65002
 neighbor 172.22.22.200 description bc-cache2
 neighbor 172.23.23.129 remote-as 65004
 neighbor 172.23.23.129 description bc-rslave1
 neighbor 172.23.23.100 remote-as 65005
 neighbor 172.23.23.100 description bc-rslave2
 !
 address-family ipv4 unicast
  neighbor 172.22.22.100 activate
  neighbor 172.22.22.200 activate
  neighbor 172.23.23.129 activate
  neighbor 172.23.23.100 activate
  maximum-paths 2
 exit-address-family
!
line vty
!
