frr version 8.5.2
frr defaults traditional
hostname bc-cache1
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 10.0.0.101
 no bgp ebgp-requires-policy
 neighbor 172.22.22.1 remote-as 65000
 neighbor 172.22.22.1 description isp-r1
 !
 address-family ipv4 unicast
  network 172.31.31.81/32
  neighbor 172.22.22.1 activate
 exit-address-family
!
line vty
!
