frr version 8.5.2
frr defaults traditional
hostname bc-rslave1
no ipv6 forwarding
!
router bgp 65004
 bgp router-id 10.0.0.129
 no bgp ebgp-requires-policy
 neighbor 172.23.23.1 remote-as 65000
 neighbor 172.23.23.1 description isp-r1
 !
 address-family ipv4 unicast
  network 172.30.30.85/32
  neighbor 172.23.23.1 activate
 exit-address-family
!
line vty
!
