options {
    directory "/var/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    server-id hostname;
    dnssec-validation no;
};

logging {
    channel default_log {
        file "/var/log/named.log" versions 3 size 5m;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
    };
    category default { default_log; };
    category queries { default_log; };
    category resolver { default_log; };
};

include "/etc/bind/rndc.key";
controls {
    inet 127.0.0.1 allow { localhost; } keys { "rndc-key"; };
};

view "recursive" {
    match-clients     { 172.22.22.100; 172.22.22.200; };
    allow-query       { 172.22.22.100; 172.22.22.200; };
    allow-query-cache { 172.22.22.100; 172.22.22.200; };
    allow-recursion   { 172.22.22.100; 172.22.22.200; };
    recursion yes;
    dnssec-validation no;

    zone "." {
        type hint;
        file "/etc/bind/db.root";
    };
};

view "authoritative" {
    match-clients { any; };
    recursion no;

    zone "lab.test" {
        type slave;
        file "/var/bind/sec/db.lab.test";
        masters { 172.23.23.97; };
    };
};
